from enum import Enum

class GameAction(Enum):
    INCOME = 'INCOME'
    FOREIGN_AID = 'FOREIGN AID'
    COUP = 'COUP'
    TAX = 'TAX'
    ASSASSINATE = 'ASSASSINATE'
    STEAL = 'STEAL'
    EXCHANGE = 'EXCHANGE'
    BLOCK_FOREIGN_AID = 'BLOCK FOREIGN AID'
    BLOCK_ASSASSINATION = 'BLOCK ASSASSINATION'
    BLOCK_STEALING = 'BLOCK STEALING'

     
