from enum import Enum


class GameState(str, Enum):
    WAITING_FOR_ACTION = "WAITING_FOR_ACTION"
    WAITING_FOR_PLAYERS = "WAITING_FOR_PLAYERS"
    ACTION_DECLARED = "ACTION_DECLARED"
    BLOCK_DECLARED = "BLOCK_DECLARED"
    CHALLENGE_HANDLE = "CHALLENGE_HANDLE"
    GAME_OVER = "GAME_OVER"
    PENDING_EXCHANGE = "PENDING_EXCHANGE"
    INFLUENCE_SELECTION_PENDING = "INFLUENCE_SELECTION_PENDING"
