from enum import Enum

class GameActions(Enum):
    INCOME = 'INCOME'
    FOREIGN_AID = 'FOREIGN AID'
    COUP = 'COUP'
    TAX = 'TAX'
    ASSASSINATE = 'ASSASSINATE'
    STEAL = 'STEAL'
    EXCHANGE = 'EXCHANGE'
    BLOCK_FOREIGN_AID = 'BLOCK FOREIGN AID'
    BLCOK_ASSASSINATION = 'BLOCK ASSASSINATION'
    BLOCK_STEAL = 'BLOCK STEAL'

     
