from enum import Enum

class GameState(Enum):
    WAITING_FOR_ACTION = "WAITING FOR ACTION"
    WAITING_FOR_PLAYERS = "WAITING FOR PLAYERS"
    ACTION_DECLARED = "ACTION DECLARED"
    BLOCK_DECLARED = "BLOCK DECLARED"
    CHALLENGE_HANDLE = "CHALLENGE HANDLE"
    GAME_OVER = "GAME OVER"
